export const featureConfigs = {
  'cell-towers': {
    title: 'Cell Towers',
    subtitle: 'Manage cell tower infrastructure, placement, and capacity optimization',
    endpoint: 'cell-towers',
    aiEndpoint: 'tower-optimization',
    aiTitle: 'Cell Tower Placement Optimization',
    icon: '\u{1F4E1}',
    columns: [
      { key: 'name', label: 'Tower Name' },
      { key: 'tower_type', label: 'Type' },
      { key: 'region', label: 'Region' },
      { key: 'frequency_band', label: 'Band' },
      { key: 'max_capacity', label: 'Max Capacity', format: 'number' },
      { key: 'current_load', label: 'Current Load', format: 'number' },
      { key: 'height_meters', label: 'Height (m)' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'name', label: 'Tower Name', type: 'text', placeholder: 'e.g., Tower Alpha-1' },
      { name: 'latitude', label: 'Latitude', type: 'number', placeholder: '40.7128' },
      { name: 'longitude', label: 'Longitude', type: 'number', placeholder: '-74.0060' },
      { name: 'tower_type', label: 'Tower Type', type: 'select', options: ['Macro', 'Small Cell', 'Micro', 'DAS', 'Femtocell'] },
      { name: 'height_meters', label: 'Height (meters)', type: 'number', placeholder: '45.0' },
      { name: 'frequency_band', label: 'Frequency Band', type: 'select', options: ['700 MHz', '850 MHz', '1900 MHz', '2100 MHz', '2500 MHz', '3500 MHz', '28 GHz', '39 GHz'] },
      { name: 'max_capacity', label: 'Max Capacity (users)', type: 'number', placeholder: '5000' },
      { name: 'current_load', label: 'Current Load (users)', type: 'number', placeholder: '3000' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'warning', 'critical', 'maintenance', 'offline'] },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'New York Metro' },
      { name: 'installed_date', label: 'Install Date', type: 'date' },
      { name: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Additional notes...' },
    ],
  },

  'bandwidth-allocations': {
    title: 'Bandwidth Allocations',
    subtitle: 'Manage bandwidth distribution across services, regions, and priority tiers',
    endpoint: 'bandwidth-allocations',
    aiEndpoint: 'bandwidth-analysis',
    aiTitle: 'Bandwidth Allocation Optimization',
    icon: '\u{1F4CA}',
    columns: [
      { key: 'name', label: 'Allocation Name' },
      { key: 'region', label: 'Region' },
      { key: 'service_type', label: 'Service Type' },
      { key: 'allocated_bandwidth_mbps', label: 'Allocated (Mbps)', format: 'number' },
      { key: 'used_bandwidth_mbps', label: 'Used (Mbps)', format: 'number' },
      { key: 'priority_level', label: 'Priority' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'name', label: 'Allocation Name', type: 'text', placeholder: 'e.g., Enterprise Gold - NYC' },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'New York Metro' },
      { name: 'allocated_bandwidth_mbps', label: 'Allocated Bandwidth (Mbps)', type: 'number', placeholder: '10000' },
      { name: 'used_bandwidth_mbps', label: 'Used Bandwidth (Mbps)', type: 'number', placeholder: '7500' },
      { name: 'priority_level', label: 'Priority Level', type: 'select', options: ['1', '2', '3', '4', '5'] },
      { name: 'service_type', label: 'Service Type', type: 'select', options: ['Enterprise', 'Consumer', 'IoT', 'Emergency', '5G Premium', 'Government', 'Healthcare', 'Education', 'Industrial', 'Utility', 'Transit', 'Retail', 'Event', 'Backup'] },
      { name: 'allocation_date', label: 'Allocation Date', type: 'date' },
      { name: 'expiry_date', label: 'Expiry Date', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'warning', 'standby', 'expired'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'rollout-plans': {
    title: '5G Rollout Plans',
    subtitle: 'Plan and track 5G technology deployment across regions and phases',
    endpoint: 'rollout-plans',
    aiEndpoint: 'rollout-analysis',
    aiTitle: '5G Rollout Strategy Analysis',
    icon: '\u{1F680}',
    columns: [
      { key: 'name', label: 'Plan Name' },
      { key: 'region', label: 'Region' },
      { key: 'technology', label: 'Technology' },
      { key: 'phase', label: 'Phase' },
      { key: 'budget_millions', label: 'Budget ($M)', format: 'decimal' },
      { key: 'towers_completed', label: 'Towers Done', format: 'number' },
      { key: 'towers_planned', label: 'Planned', format: 'number' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'name', label: 'Plan Name', type: 'text', placeholder: 'NYC 5G Phase 1' },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'New York Metro' },
      { name: 'technology', label: 'Technology', type: 'select', options: ['5G NR', '5G NR SA', '5G mmWave', '5G FWA'] },
      { name: 'phase', label: 'Phase', type: 'select', options: ['Phase 1', 'Phase 2', 'Phase 3', 'Phase 4'] },
      { name: 'start_date', label: 'Start Date', type: 'date' },
      { name: 'end_date', label: 'End Date', type: 'date' },
      { name: 'budget_millions', label: 'Budget (Millions $)', type: 'number', placeholder: '100' },
      { name: 'towers_planned', label: 'Towers Planned', type: 'number', placeholder: '200' },
      { name: 'towers_completed', label: 'Towers Completed', type: 'number', placeholder: '0' },
      { name: 'population_covered', label: 'Population Covered', type: 'number', placeholder: '1000000' },
      { name: 'status', label: 'Status', type: 'select', options: ['planned', 'in_progress', 'completed', 'on_hold'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'coverage-gaps': {
    title: 'Coverage Gaps',
    subtitle: 'Identify and remediate network coverage gaps affecting service quality',
    endpoint: 'coverage-gaps',
    aiEndpoint: 'coverage-analysis',
    aiTitle: 'Coverage Gap Remediation Analysis',
    icon: '\u{1F4CD}',
    columns: [
      { key: 'name', label: 'Gap Name' },
      { key: 'region', label: 'Region' },
      { key: 'gap_type', label: 'Gap Type' },
      { key: 'severity', label: 'Severity', badge: true },
      { key: 'affected_population', label: 'Affected Pop.', format: 'number' },
      { key: 'radius_km', label: 'Radius (km)' },
      { key: 'signal_strength_dbm', label: 'Signal (dBm)' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'name', label: 'Gap Name', type: 'text', placeholder: 'South Bronx Dead Zone' },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'New York Metro' },
      { name: 'latitude', label: 'Latitude', type: 'number', placeholder: '40.8176' },
      { name: 'longitude', label: 'Longitude', type: 'number', placeholder: '-73.9209' },
      { name: 'radius_km', label: 'Radius (km)', type: 'number', placeholder: '2.5' },
      { name: 'affected_population', label: 'Affected Population', type: 'number', placeholder: '125000' },
      { name: 'signal_strength_dbm', label: 'Signal Strength (dBm)', type: 'number', placeholder: '-110' },
      { name: 'gap_type', label: 'Gap Type', type: 'select', options: ['No Coverage', 'Weak Signal', 'Poor Coverage', 'Indoor Gap'] },
      { name: 'severity', label: 'Severity', type: 'select', options: ['critical', 'high', 'medium', 'low'] },
      { name: 'recommended_solution', label: 'Recommended Solution', type: 'textarea' },
      { name: 'status', label: 'Status', type: 'select', options: ['identified', 'in_progress', 'planned', 'resolved'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'demand-forecasts': {
    title: 'Demand Forecasts',
    subtitle: 'AI-powered demand prediction for capacity planning and investment decisions',
    endpoint: 'demand-forecasts',
    aiEndpoint: 'demand-analysis',
    aiTitle: 'Demand Forecasting & Capacity Planning',
    icon: '\u{1F4C8}',
    columns: [
      { key: 'name', label: 'Forecast Name' },
      { key: 'region', label: 'Region' },
      { key: 'data_type', label: 'Data Type' },
      { key: 'current_demand_gbps', label: 'Current (Gbps)', format: 'decimal' },
      { key: 'predicted_demand_gbps', label: 'Predicted (Gbps)', format: 'decimal' },
      { key: 'growth_rate_percent', label: 'Growth %', format: 'percent' },
      { key: 'confidence_level', label: 'Confidence %', format: 'percent' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'name', label: 'Forecast Name', type: 'text', placeholder: 'NYC Q1 2025 Forecast' },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'New York Metro' },
      { name: 'forecast_period', label: 'Forecast Period', type: 'text', placeholder: 'Q1 2025' },
      { name: 'current_demand_gbps', label: 'Current Demand (Gbps)', type: 'number', placeholder: '850' },
      { name: 'predicted_demand_gbps', label: 'Predicted Demand (Gbps)', type: 'number', placeholder: '1020' },
      { name: 'growth_rate_percent', label: 'Growth Rate (%)', type: 'number', placeholder: '20' },
      { name: 'confidence_level', label: 'Confidence Level (%)', type: 'number', placeholder: '92.5' },
      { name: 'data_type', label: 'Data Type', type: 'select', options: ['Mobile Data', 'Video Streaming', 'IoT Traffic', 'Industrial IoT', 'Residential Broadband', 'Gaming/Low Latency', 'Enterprise Cloud', 'AR/VR Applications', 'Event Surge', 'Secure Communications', '5G Traffic', 'Healthcare/Telemedicine'] },
      { name: 'peak_hour', label: 'Peak Hour', type: 'text', placeholder: '18:00-20:00' },
      { name: 'methodology', label: 'Methodology', type: 'text', placeholder: 'ARIMA + ML Ensemble' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'archived', 'draft'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'network-load': {
    title: 'Network Load',
    subtitle: 'Monitor and optimize traffic distribution across network nodes',
    endpoint: 'network-load',
    aiEndpoint: 'load-analysis',
    aiTitle: 'Network Load Balancing Optimization',
    icon: '\u2696\uFE0F',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'node_name', label: 'Node' },
      { key: 'region', label: 'Region' },
      { key: 'current_load_percent', label: 'Load %', format: 'percent' },
      { key: 'max_capacity_gbps', label: 'Capacity (Gbps)' },
      { key: 'avg_latency_ms', label: 'Latency (ms)' },
      { key: 'active_connections', label: 'Connections', format: 'number' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'name', label: 'Name', type: 'text', placeholder: 'NYC Core Router A' },
      { name: 'node_name', label: 'Node Name', type: 'text', placeholder: 'NYC-CORE-A' },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'New York Metro' },
      { name: 'current_load_percent', label: 'Current Load (%)', type: 'number', placeholder: '78.5' },
      { name: 'max_capacity_gbps', label: 'Max Capacity (Gbps)', type: 'number', placeholder: '100' },
      { name: 'avg_latency_ms', label: 'Avg Latency (ms)', type: 'number', placeholder: '12.3' },
      { name: 'packet_loss_percent', label: 'Packet Loss (%)', type: 'number', placeholder: '0.01' },
      { name: 'active_connections', label: 'Active Connections', type: 'number', placeholder: '450000' },
      { name: 'balancing_strategy', label: 'Balancing Strategy', type: 'select', options: ['Weighted Round Robin', 'Least Connections', 'IP Hash', 'Round Robin', 'Weighted Least Connections', 'BGP ECMP', 'Geographic', 'Policy-based', 'Priority Queue', 'ECMP + Anycast', 'Application-aware', 'Content-aware', 'Priority + Encryption'] },
      { name: 'status', label: 'Status', type: 'select', options: ['normal', 'warning', 'critical'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'spectrum-management': {
    title: 'Spectrum Management',
    subtitle: 'Manage frequency spectrum licenses, utilization, and assignments',
    endpoint: 'spectrum-management',
    aiEndpoint: 'spectrum-analysis',
    aiTitle: 'Spectrum Optimization Analysis',
    icon: '\u{1F4F6}',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'frequency_band', label: 'Band' },
      { key: 'bandwidth_mhz', label: 'BW (MHz)' },
      { key: 'technology', label: 'Technology' },
      { key: 'region', label: 'Region' },
      { key: 'utilization_percent', label: 'Utilization %', format: 'percent' },
      { key: 'interference_level', label: 'Interference' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'name', label: 'Name', type: 'text', placeholder: 'Low-Band 700MHz NYC' },
      { name: 'frequency_band', label: 'Frequency Band', type: 'text', placeholder: '700 MHz' },
      { name: 'bandwidth_mhz', label: 'Bandwidth (MHz)', type: 'number', placeholder: '20' },
      { name: 'license_holder', label: 'License Holder', type: 'text', placeholder: 'TelecomCorp' },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'New York Metro' },
      { name: 'technology', label: 'Technology', type: 'select', options: ['4G LTE', '4G LTE-A', '5G NR', '5G NR / LTE', '5G mmWave', 'LTE Band 14', 'LTE-LAA', '6G Research'] },
      { name: 'license_start', label: 'License Start', type: 'date' },
      { name: 'license_end', label: 'License End', type: 'date' },
      { name: 'utilization_percent', label: 'Utilization (%)', type: 'number', placeholder: '85' },
      { name: 'interference_level', label: 'Interference Level', type: 'select', options: ['low', 'medium', 'high'] },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'reserved', 'expired'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'qos-monitoring': {
    title: 'QoS Monitoring',
    subtitle: 'Track quality of service metrics and SLA compliance across services',
    endpoint: 'qos-monitoring',
    aiEndpoint: 'qos-analysis',
    aiTitle: 'QoS & SLA Compliance Analysis',
    icon: '\u2705',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'service_name', label: 'Service' },
      { key: 'region', label: 'Region' },
      { key: 'latency_ms', label: 'Latency (ms)' },
      { key: 'throughput_mbps', label: 'Throughput (Mbps)', format: 'number' },
      { key: 'availability_percent', label: 'Avail %', format: 'percent' },
      { key: 'violation_count', label: 'Violations' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'name', label: 'Name', type: 'text', placeholder: 'VoLTE NYC Primary' },
      { name: 'service_name', label: 'Service Name', type: 'text', placeholder: 'Voice over LTE' },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'New York Metro' },
      { name: 'latency_ms', label: 'Latency (ms)', type: 'number', placeholder: '25' },
      { name: 'jitter_ms', label: 'Jitter (ms)', type: 'number', placeholder: '5.2' },
      { name: 'packet_loss_percent', label: 'Packet Loss (%)', type: 'number', placeholder: '0.01' },
      { name: 'throughput_mbps', label: 'Throughput (Mbps)', type: 'number', placeholder: '64' },
      { name: 'availability_percent', label: 'Availability (%)', type: 'number', placeholder: '99.99' },
      { name: 'sla_target', label: 'SLA Target', type: 'text', placeholder: 'Latency < 50ms, Loss < 0.1%' },
      { name: 'violation_count', label: 'Violation Count', type: 'number', placeholder: '0' },
      { name: 'status', label: 'Status', type: 'select', options: ['compliant', 'warning', 'violation'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'infrastructure-costs': {
    title: 'Infrastructure Costs',
    subtitle: 'Analyze and optimize infrastructure investment decisions and ROI',
    endpoint: 'infrastructure-costs',
    aiEndpoint: 'cost-analysis',
    aiTitle: 'Infrastructure Cost Optimization',
    icon: '\u{1F4B0}',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'category', label: 'Category' },
      { key: 'region', label: 'Region' },
      { key: 'capex_millions', label: 'CapEx ($M)', format: 'decimal' },
      { key: 'opex_monthly_thousands', label: 'OpEx/Mo ($K)', format: 'decimal' },
      { key: 'roi_percent', label: 'ROI %', format: 'percent' },
      { key: 'vendor', label: 'Vendor' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'name', label: 'Name', type: 'text', placeholder: 'NYC 5G Macro Towers' },
      { name: 'category', label: 'Category', type: 'select', options: ['Tower Infrastructure', 'Small Cells', 'Fiber Optic', 'Data Center', 'Power/Energy', 'DAS', 'Network Equipment', 'Site Hardening', 'WiFi Infrastructure', 'Edge Compute', 'Tower Leasing', 'Security', 'Smart Infrastructure', 'Software/OSS', 'Transit DAS'] },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'New York Metro' },
      { name: 'capex_millions', label: 'CapEx (Millions $)', type: 'number', placeholder: '45' },
      { name: 'opex_monthly_thousands', label: 'Monthly OpEx (Thousands $)', type: 'number', placeholder: '180' },
      { name: 'roi_percent', label: 'ROI (%)', type: 'number', placeholder: '22.5' },
      { name: 'payback_period_months', label: 'Payback Period (Months)', type: 'number', placeholder: '24' },
      { name: 'vendor', label: 'Vendor', type: 'text', placeholder: 'Ericsson' },
      { name: 'contract_start', label: 'Contract Start', type: 'date' },
      { name: 'contract_end', label: 'Contract End', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'planned', 'in_progress', 'completed'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'signal-interference': {
    title: 'Signal Interference',
    subtitle: 'Detect, analyze, and mitigate RF signal interference incidents',
    endpoint: 'signal-interference',
    aiEndpoint: 'interference-analysis',
    aiTitle: 'Signal Interference Mitigation Analysis',
    icon: '\u26A0\uFE0F',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'source_type', label: 'Source Type' },
      { key: 'region', label: 'Region' },
      { key: 'interference_type', label: 'Type' },
      { key: 'interference_dbm', label: 'Level (dBm)' },
      { key: 'affected_users', label: 'Affected Users', format: 'number' },
      { key: 'severity', label: 'Severity', badge: true },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'name', label: 'Name', type: 'text', placeholder: 'JFK Airport Radar' },
      { name: 'source_type', label: 'Source Type', type: 'select', options: ['Radar System', 'Signal Booster', 'Electromagnetic', 'Industrial', 'Solar Equipment', 'Broadcasting', 'Maritime', 'Multipath', 'Medical Equipment', 'Backhaul Link', 'Jamming', 'Unknown', 'Entertainment', 'Wind Energy', 'Construction'] },
      { name: 'affected_tower', label: 'Affected Tower', type: 'text', placeholder: 'Tower Beta-2' },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'New York Metro' },
      { name: 'frequency_mhz', label: 'Frequency (MHz)', type: 'number', placeholder: '2700' },
      { name: 'interference_dbm', label: 'Interference Level (dBm)', type: 'number', placeholder: '-65' },
      { name: 'affected_area_km2', label: 'Affected Area (km2)', type: 'number', placeholder: '15' },
      { name: 'affected_users', label: 'Affected Users', type: 'number', placeholder: '85000' },
      { name: 'interference_type', label: 'Interference Type', type: 'select', options: ['Adjacent Channel', 'Co-Channel', 'Electromagnetic', 'Intermodulation', 'Broadband Noise', 'Out-of-Band', 'Multipath', 'Cross-Polar', 'Intentional Jamming', 'Unknown Source', 'Scattering', 'Blocking/Reflection'] },
      { name: 'mitigation_strategy', label: 'Mitigation Strategy', type: 'textarea' },
      { name: 'severity', label: 'Severity', type: 'select', options: ['critical', 'high', 'medium', 'low'] },
      { name: 'status', label: 'Status', type: 'select', options: ['detected', 'mitigating', 'resolved'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'network-alarms': {
    title: 'Network Alarms',
    subtitle: 'Monitor, triage, and resolve network alarms and incidents',
    endpoint: 'network-alarms',
    aiEndpoint: 'alarm-analysis',
    aiTitle: 'Network Alarm & Incident Analysis',
    icon: '\u{1F6A8}',
    columns: [
      { key: 'name', label: 'Alarm Name' },
      { key: 'alarm_type', label: 'Type' },
      { key: 'source_node', label: 'Source Node' },
      { key: 'region', label: 'Region' },
      { key: 'severity', label: 'Severity', badge: true },
      { key: 'category', label: 'Category' },
      { key: 'assigned_to', label: 'Assigned To' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'name', label: 'Alarm Name', type: 'text', placeholder: 'NYC Core Link Flap' },
      { name: 'alarm_type', label: 'Alarm Type', type: 'select', options: ['Link Failure', 'Environmental', 'Protocol', 'Power', 'Performance', 'Security', 'Capacity', 'Configuration', 'Traffic'] },
      { name: 'source_node', label: 'Source Node', type: 'text', placeholder: 'NYC-CORE-A' },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'New York Metro' },
      { name: 'severity', label: 'Severity', type: 'select', options: ['critical', 'major', 'minor', 'warning'] },
      { name: 'category', label: 'Category', type: 'select', options: ['Connectivity', 'Environmental', 'Routing', 'Power', 'Performance', 'Security', 'Storage', 'Configuration', 'Traffic', 'Licensing'] },
      { name: 'description', label: 'Description', type: 'textarea', placeholder: 'Describe the alarm condition...' },
      { name: 'assigned_to', label: 'Assigned To', type: 'text', placeholder: 'NOC Team Alpha' },
      { name: 'root_cause', label: 'Root Cause', type: 'textarea' },
      { name: 'affected_services', label: 'Affected Services', type: 'text', placeholder: 'Voice, Data, Enterprise VPN' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'acknowledged', 'resolved'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'subscriber-analytics': {
    title: 'Subscriber Analytics',
    subtitle: 'Analyze subscriber metrics, churn, ARPU, and customer satisfaction',
    endpoint: 'subscriber-analytics',
    aiEndpoint: 'subscriber-analysis',
    aiTitle: 'Subscriber Growth & Retention Analysis',
    icon: '\u{1F465}',
    columns: [
      { key: 'name', label: 'Segment Name' },
      { key: 'region', label: 'Region' },
      { key: 'plan_type', label: 'Plan Type' },
      { key: 'total_subscribers', label: 'Total Subs', format: 'number' },
      { key: 'churn_rate_percent', label: 'Churn %', format: 'percent' },
      { key: 'avg_revenue_per_user', label: 'ARPU ($)', format: 'decimal' },
      { key: 'satisfaction_score', label: 'CSAT' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'name', label: 'Segment Name', type: 'text', placeholder: 'NYC Postpaid Premium' },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'New York Metro' },
      { name: 'plan_type', label: 'Plan Type', type: 'select', options: ['Postpaid Premium', 'Postpaid Family', 'Prepaid Basic', 'Enterprise', '5G Unlimited', 'Student', 'Business Pro', 'Business Plus', 'Roaming/Visitor', 'Academic Bundle', 'Developer API', 'Government', 'FirstNet', 'IoT/M2M', 'Senior Basic'] },
      { name: 'total_subscribers', label: 'Total Subscribers', type: 'number', placeholder: '850000' },
      { name: 'active_subscribers', label: 'Active Subscribers', type: 'number', placeholder: '820000' },
      { name: 'churn_rate_percent', label: 'Churn Rate (%)', type: 'number', placeholder: '1.2' },
      { name: 'avg_revenue_per_user', label: 'Avg Revenue Per User ($)', type: 'number', placeholder: '95.50' },
      { name: 'data_usage_avg_gb', label: 'Avg Data Usage (GB)', type: 'number', placeholder: '45' },
      { name: 'satisfaction_score', label: 'Satisfaction Score (1-10)', type: 'number', placeholder: '8.5' },
      { name: 'support_tickets', label: 'Support Tickets', type: 'number', placeholder: '12500' },
      { name: 'measurement_period', label: 'Measurement Period', type: 'text', placeholder: 'Q1 2025' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'archived'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'fiber-routes': {
    title: 'Fiber Optic Routes',
    subtitle: 'Manage fiber optic network topology, capacity, and route planning',
    endpoint: 'fiber-routes',
    aiEndpoint: 'fiber-analysis',
    aiTitle: 'Fiber Network Topology & Capacity Analysis',
    icon: '\u{1F310}',
    columns: [
      { key: 'name', label: 'Route Name' },
      { key: 'route_type', label: 'Type' },
      { key: 'start_location', label: 'Start' },
      { key: 'end_location', label: 'End' },
      { key: 'length_km', label: 'Length (km)' },
      { key: 'capacity_tbps', label: 'Capacity (Tbps)' },
      { key: 'current_utilization_percent', label: 'Util %', format: 'percent' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'name', label: 'Route Name', type: 'text', placeholder: 'NYC Metro Ring A' },
      { name: 'route_type', label: 'Route Type', type: 'select', options: ['Metro Ring', 'Metro Core', 'Metro', 'Long Haul', 'Regional', 'Submarine', 'Campus', 'Secure'] },
      { name: 'start_location', label: 'Start Location', type: 'text', placeholder: 'Manhattan Hub' },
      { name: 'end_location', label: 'End Location', type: 'text', placeholder: 'Brooklyn POP' },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'New York Metro' },
      { name: 'length_km', label: 'Length (km)', type: 'number', placeholder: '45' },
      { name: 'fiber_count', label: 'Fiber Count', type: 'number', placeholder: '288' },
      { name: 'capacity_tbps', label: 'Capacity (Tbps)', type: 'number', placeholder: '38.4' },
      { name: 'current_utilization_percent', label: 'Utilization (%)', type: 'number', placeholder: '72' },
      { name: 'installation_date', label: 'Installation Date', type: 'date' },
      { name: 'vendor', label: 'Vendor', type: 'text', placeholder: 'Corning' },
      { name: 'redundancy_type', label: 'Redundancy Type', type: 'select', options: ['SONET Ring', 'Dual Ring', 'Diverse Path', 'Linear + Backup', 'Single Path', 'Submarine + Land', 'Dual Submarine', 'Ring', 'Bridge + Tunnel', 'Mesh', 'Hardened Ring', 'Star', 'Diverse Route'] },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'planned', 'under_construction', 'decommissioned'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'maintenance-schedules': {
    title: 'Maintenance Schedules',
    subtitle: 'Plan, track, and optimize network maintenance windows and activities',
    endpoint: 'maintenance-schedules',
    aiEndpoint: 'maintenance-analysis',
    aiTitle: 'Maintenance Planning & Optimization',
    icon: '\u{1F527}',
    columns: [
      { key: 'name', label: 'Maintenance Name' },
      { key: 'maintenance_type', label: 'Type' },
      { key: 'target_asset', label: 'Target Asset' },
      { key: 'region', label: 'Region' },
      { key: 'impact_level', label: 'Impact', badge: true },
      { key: 'affected_users', label: 'Affected Users', format: 'number' },
      { key: 'assigned_team', label: 'Team' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'name', label: 'Maintenance Name', type: 'text', placeholder: 'NYC Core Router Upgrade' },
      { name: 'maintenance_type', label: 'Type', type: 'select', options: ['Software Upgrade', 'Hardware Replacement', 'Fiber Maintenance', 'Preventive', 'Optimization', 'Migration', 'Inspection', 'Security', 'Capacity Upgrade', 'Configuration', 'Installation'] },
      { name: 'target_asset', label: 'Target Asset', type: 'text', placeholder: 'NYC-CORE-A' },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'New York Metro' },
      { name: 'scheduled_start', label: 'Scheduled Start', type: 'datetime-local' },
      { name: 'scheduled_end', label: 'Scheduled End', type: 'datetime-local' },
      { name: 'impact_level', label: 'Impact Level', type: 'select', options: ['critical', 'high', 'medium', 'low'] },
      { name: 'affected_users', label: 'Affected Users', type: 'number', placeholder: '450000' },
      { name: 'assigned_team', label: 'Assigned Team', type: 'text', placeholder: 'Network Engineering' },
      { name: 'vendor', label: 'Vendor', type: 'text', placeholder: 'Cisco' },
      { name: 'cost_estimate', label: 'Cost Estimate ($)', type: 'number', placeholder: '15000' },
      { name: 'status', label: 'Status', type: 'select', options: ['scheduled', 'approved', 'in_progress', 'completed', 'cancelled'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'energy-consumption': {
    title: 'Energy Consumption',
    subtitle: 'Monitor energy usage, costs, carbon footprint, and sustainability metrics',
    endpoint: 'energy-consumption',
    aiEndpoint: 'energy-analysis',
    aiTitle: 'Energy & Sustainability Analysis',
    icon: '\u26A1',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'site_name', label: 'Site' },
      { key: 'site_type', label: 'Type' },
      { key: 'region', label: 'Region' },
      { key: 'monthly_kwh', label: 'Monthly kWh', format: 'number' },
      { key: 'monthly_cost', label: 'Monthly Cost ($)', format: 'number' },
      { key: 'renewable_percent', label: 'Renewable %', format: 'percent' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'name', label: 'Name', type: 'text', placeholder: 'NYC Data Center Power' },
      { name: 'site_name', label: 'Site Name', type: 'text', placeholder: 'NYC-DC-1' },
      { name: 'site_type', label: 'Site Type', type: 'select', options: ['Data Center', 'Core Data Center', 'Edge Data Center', 'Small DC', 'Central Office', 'Tower Cluster', 'Tower + Solar', 'Remote Towers', 'Hardened Towers', 'Campus', 'Secure Facility', 'Smart Infrastructure', 'Transit Infrastructure'] },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'New York Metro' },
      { name: 'monthly_kwh', label: 'Monthly Consumption (kWh)', type: 'number', placeholder: '450000' },
      { name: 'cost_per_kwh', label: 'Cost per kWh ($)', type: 'number', placeholder: '0.18' },
      { name: 'monthly_cost', label: 'Monthly Cost ($)', type: 'number', placeholder: '81000' },
      { name: 'renewable_percent', label: 'Renewable Energy (%)', type: 'number', placeholder: '15' },
      { name: 'pue_ratio', label: 'PUE Ratio', type: 'number', placeholder: '1.45' },
      { name: 'carbon_tons_monthly', label: 'Carbon (Tons/Month)', type: 'number', placeholder: '195' },
      { name: 'cooling_type', label: 'Cooling Type', type: 'select', options: ['Chilled Water', 'Precision AC', 'Free Cooling + AC', 'Free Air Cooling', 'Liquid Cooling', 'Evaporative', 'Passive Air', 'Passive + Heater', 'Split AC', 'CRAC Units', 'Redundant AC', 'Tunnel Ventilation', 'None'] },
      { name: 'backup_power', label: 'Backup Power', type: 'text', placeholder: 'Diesel Generator + UPS' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'planned', 'decommissioned'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
};
